### ISSUE TITLE
Create Login Screen

### ISSUE THREAD

**Issue by davidemarcoli** [davidemarcoli/GradeManager-Mobile#1]

**Comment by lazarpe** [comment]
TODO: @davidemarcoli 
Need to adjust input fields once @lazarpe update it's component

**Comment by lazarpe** [comment]
TODO: @davidemarcoli 
Need to add navigation to registration page if user doesn't have an account like in the image below


![Image](https://user-images.githubusercontent.com/69906272/174481423-4e349993-003f-4330-b0e0-0277eb5ec1e1.png)
